# Generated by Django 5.2 on 2025-04-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BeamToBeamEndPlate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=100)),
                ("engineer_name", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("beam_section", models.CharField(max_length=100)),
                ("end_plate_thickness", models.FloatField()),
                ("bolt_diameter", models.FloatField()),
                ("bolt_type", models.CharField(max_length=50)),
                ("shear_force", models.FloatField()),
                ("bending_moment", models.FloatField()),
                ("axial_force", models.FloatField()),
            ],
        ),
    ]
