# Generated by Django 5.2 on 2025-04-09 18:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="beamtobeamendplate",
            old_name="axial_force",
            new_name="axialForce",
        ),
        migrations.RenameField(
            model_name="beamtobeamendplate",
            old_name="beam_section",
            new_name="beamSection",
        ),
        migrations.RenameField(
            model_name="beamtobeamendplate",
            old_name="bending_moment",
            new_name="bendingMoment",
        ),
        migrations.RenameField(
            model_name="beamtobeamendplate",
            old_name="bolt_diameter",
            new_name="boltDiameter",
        ),
        migrations.RenameField(
            model_name="beamtobeamendplate",
            old_name="engineer_name",
            new_name="material",
        ),
        migrations.RenameField(
            model_name="beamtobeamendplate",
            old_name="end_plate_thickness",
            new_name="shearForce",
        ),
        migrations.RenameField(
            model_name="beamtobeamendplate",
            old_name="shear_force",
            new_name="webThickness",
        ),
        migrations.RemoveField(
            model_name="beamtobeamendplate",
            name="bolt_type",
        ),
        migrations.RemoveField(
            model_name="beamtobeamendplate",
            name="date",
        ),
        migrations.RemoveField(
            model_name="beamtobeamendplate",
            name="project_name",
        ),
        migrations.AddField(
            model_name="beamtobeamendplate",
            name="boltClass",
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
